default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vendelo_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: vendelo_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: vendelo_production
  username: postgres
  password: <%= ENV["VENDELO_DATABASE_PASSWORD"] %>
